# Generated by Django 4.1.7 on 2023-04-24 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='shipper',
        ),
        migrations.RemoveField(
            model_name='like',
            name='users',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customers',
        ),
        migrations.RemoveField(
            model_name='order',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shippers',
        ),
        migrations.RemoveField(
            model_name='post',
            name='customers',
        ),
        migrations.RemoveField(
            model_name='post',
            name='shippers',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='users',
        ),
        migrations.DeleteModel(
            name='Auction',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
