# Generated by Django 4.1.7 on 2023-04-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_customer',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('shipper', 'Shipper'), ('customer', 'Customer')], max_length=10, null=True),
        ),
    ]
