# Generated by Django 4.1.7 on 2023-05-08 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_remove_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='shippers',
            new_name='auctions',
        ),
    ]
