# Generated by Django 4.1.7 on 2023-05-08 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_rename_shippers_post_auctions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='auctions',
            new_name='shippers',
        ),
    ]
